Numpy is a fundamental library for scientific computing in python. It proives support for arrays and matirces, alon with a collection of mathematical functions to operate on these data structures.

In [2]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
print(arr.shape)

Original array: [1 2 3 4 5]
(5,)


In [ ]:
arr = arr.reshape(5,1)
print("Reshaped array:\n", arr)
print("New shape:", arr.shape) # shape: (rows, columns)

Reshaped array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
New shape: (5, 1)


In [10]:
np.arange(0, 10, 2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3, 3))  # Create a 3x3 array of ones
np.zeros((2, 4))  # Create a 2x4 array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.eye(3)  # Create a 3x3 identity matrix  

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
# Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])

print(f"Addtion: {arr1  + arr2}")
print(f"substraction: {arr1-arr2}")
print(f"multiplication: {arr1*arr2}")
print(f"division: {arr1/arr2}")

Addtion: [ 6  8 10 12 14]
substraction: [-4 -4 -4 -4 -4]
multiplication: [ 5 12 21 32 45]
division: [0.2        0.33333333 0.42857143 0.5        0.55555556]


In [5]:
#universal functions
print(f"Square root: {np.sqrt(arr1)}")
print(f"Exponent: {np.exp(arr1)}")
print(f"Logarithm: {np.log(arr1)}")
print(f"Logarithm base 10: {np.log10(arr1)}")
print(f"sin: {np.sin(arr1)}")
print(f"cos: {np.cos(arr1)}")

Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponent: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Logarithm base 10: [0.         0.30103    0.47712125 0.60205999 0.69897   ]
sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [8]:
#array slicing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original array:\n", arr)



Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# arr[row][col]
print("Element at (0, 1):", arr[0][1])  # Accessing element at row 0, column 1
print("Row 1:", arr[1])  # Accessing the entire row 1
print("Column 2:", arr[:, 2])  # Accessing the entire column 2
print("Sub-array (0:2, 1:3):\n", arr[0:2, 1:3])  # Accessing a sub-array from row 0 to 1 and column 1 to 2
print("Last row:", arr[-1])  # Accessing the last row
print("Last column:", arr[:, -1])   # Accessing the last column
print("First two rows:\n", arr[:2])  # Accessing the first two rows
print("First two columns:\n", arr[:, :2])  # Accessing the first two columns
print("Elements greater than 5:\n", arr[arr > 5])   

Element at (0, 1): 2
Row 1: [5 6 7 8]
Column 2: [ 3  7 11]
Sub-array (0:2, 1:3):
 [[2 3]
 [6 7]]
Last row: [ 9 10 11 12]
Last column: [ 4  8 12]
First two rows:
 [[1 2 3 4]
 [5 6 7 8]]
First two columns:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Elements greater than 5:
 [ 6  7  8  9 10 11 12]


In [14]:
# Statistical operations
data = np.array([1,2,3,4,5])

print("Mean:", np.mean(data))  # Mean
print("Median:", np.median(data))  # Median
print("Standard Deviation:", np.std(data))  # Standard Deviation   
print("Variance:", np.var(data))  # Variance

#Normalization: converting the data in such a way that it has a mean of 0 and standard deviation of 1
mean = np.mean(data)
std = np.std(data)
normalized_data = (data - mean) / std
print(f"Normalized data: {normalized_data}")

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
